"""Analyze structured logs generated by yt-best-video."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


LOGS_DIR = Path(__file__).parent / "logs"

STEP_ORDER = [
    "worker_automatizacion_start",
    "step_wait_connections",
    "step_wait_connections_ok",
    "step_prepare_tab",
    "step_prepare_tab_ok",
    "step_check_journey_exists",
    "step_journey_found",
    "step_analyze_channels",
    "step_analyze_channels_ok",
    "step_sync_ref_title",
    "step_sync_ref_title_ok",
    "step_validate_journey",
    "step_validate_journey_result",
    "step_run_journey_start",
    "step_run_journey_dispatched",
    "step_wait_completion_start",
    "step_wait_completion_ok",
]


def load_logs(log_file: Path) -> list[dict]:
    entries: list[dict] = []
    with log_file.open(encoding="utf-8") as handle:
        for line in handle:
            line = line.strip()
            if not line:
                continue
            try:
                entries.append(json.loads(line))
            except json.JSONDecodeError:
                continue
    return entries


def load_all_logs() -> list[dict]:
    entries: list[dict] = []
    for log_file in sorted(LOGS_DIR.glob("*.log")):
        entries.extend(load_logs(log_file))
    entries.sort(key=lambda entry: entry.get("ts", ""))
    return entries


def find_last_session(entries: list[dict]) -> str | None:
    for entry in reversed(entries):
        if entry.get("event") == "worker_automatizacion_start":
            return entry.get("session")
    return None


def filter_by_session(entries: list[dict], session_id: str) -> list[dict]:
    return [entry for entry in entries if entry.get("session") == session_id]


def filter_by_execution(entries: list[dict], execution_id: str) -> list[dict]:
    return [
        entry
        for entry in entries
        if entry.get("execution_id") == execution_id or execution_id in json.dumps(entry)
    ]


def print_report(entries: list[dict]) -> None:
    errors = [entry for entry in entries if entry.get("level") in {"ERROR", "WARNING"}]
    journey_events = [
        entry
        for entry in entries
        if "journey" in entry.get("event", "").lower()
        or entry.get("event", "").startswith("step_")
    ]

    print("\n" + "=" * 70)
    print("  REPORTE DE DIAGNOSTICO - CLUSIV YT BEST VIDEO")
    print("=" * 70)

    print(f"\nTotal de entradas: {len(entries)}")
    print(f"Errores/Warnings: {len(errors)}")
    print(f"Eventos de journey: {len(journey_events)}")

    print("\nTIMELINE DEL FLUJO PRINCIPAL:")
    print("-" * 50)
    found_steps = set()
    for entry in entries:
        event = entry.get("event", "")
        if event not in STEP_ORDER:
            continue
        ts = entry.get("ts", "")[:19].replace("T", " ")
        level = entry.get("level", "INFO")
        if event.endswith("_ok") or event.endswith("_found") or event.endswith("_dispatched"):
            marker = "OK"
        elif level == "ERROR":
            marker = "ERR"
        else:
            marker = "RUN"
        print(f"  {marker:>3} [{ts}] {event}")
        found_steps.add(event)

    missing = [step for step in STEP_ORDER if step not in found_steps]
    if missing:
        print("\nPASOS NO ALCANZADOS:")
        print("  " + ", ".join(missing))
        last_found = next((step for step in reversed(STEP_ORDER) if step in found_steps), None)
        if last_found:
            print(f"  Flujo detenido en: {last_found}")

    if errors:
        print("\nERRORES Y WARNINGS DETALLADOS:")
        print("-" * 50)
        for entry in errors:
            ts = entry.get("ts", "")[:19].replace("T", " ")
            level = entry.get("level")
            event = entry.get("event", "")
            print(f"\n  [{level}] [{ts}] {event}")
            skip = {"ts", "ts_mono", "session", "level", "event"}
            for key, value in entry.items():
                if key in skip or value is None:
                    continue
                print(f"    {key}: {value}")

    ws_events = [
        entry
        for entry in entries
        if "ws_" in entry.get("event", "")
        or "connected" in entry.get("event", "")
        or "disconnected" in entry.get("event", "")
    ]
    if ws_events:
        print("\nEVENTOS DE CONEXION WEBSOCKET:")
        print("-" * 50)
        for entry in ws_events:
            ts = entry.get("ts", "")[:19].replace("T", " ")
            event = entry.get("event", "")
            port = entry.get("port") or entry.get("control_port") or entry.get("template_port")
            suffix = f" (port:{port})" if port else ""
            print(f"  [{ts}] {event}{suffix}")

    execution_ids = {entry.get("execution_id") for entry in entries if entry.get("execution_id")}
    if execution_ids:
        print(f"\nEXECUTION IDs RASTREADOS: {len(execution_ids)}")
        for execution_id in sorted(execution_ids):
            execution_entries = [entry for entry in entries if entry.get("execution_id") == execution_id]
            statuses = [
                entry.get("new_status") or entry.get("status") or entry.get("event")
                for entry in execution_entries
            ]
            compact = " -> ".join(status for status in statuses if status)
            print(f"  {execution_id}: {compact}")

    print("\n" + "=" * 70 + "\n")


def main() -> None:
    parser = argparse.ArgumentParser(description="Analizar logs de Clusiv YT Best Video")
    parser.add_argument("--session", help="Filtrar por session ID")
    parser.add_argument("--execution", help="Filtrar por execution ID")
    parser.add_argument(
        "--last-run",
        action="store_true",
        help="Analizar solo el ultimo intento de ejecucion",
    )
    args = parser.parse_args()

    if not LOGS_DIR.exists():
        print(f"No se encontro el directorio de logs: {LOGS_DIR}")
        sys.exit(1)

    all_entries = load_all_logs()
    if not all_entries:
        print("No se encontraron entradas de log.")
        sys.exit(1)

    entries = all_entries

    if args.last_run:
        session_id = find_last_session(all_entries)
        if session_id:
            print(f"Usando session ID del ultimo run: {session_id}")
            entries = filter_by_session(all_entries, session_id)
        else:
            print("No se encontro ningun run previo; se mostraran todos los logs.")

    if args.session:
        entries = filter_by_session(entries, args.session)
        print(f"Filtrando por session: {args.session}")

    if args.execution:
        entries = filter_by_execution(entries, args.execution)
        print(f"Filtrando por execution_id: {args.execution}")

    print_report(entries)


if __name__ == "__main__":
    main()